### ISSUE TITLE
Submissions open for hacktoberfest

### ISSUE THREAD

**Issue by mayurmadnani** [mayurmadnani/covidtracer#1]
Free to submit PR for any improvements. Make sure to add screenshots along with PR 

Many contributions overall are not made in the good spirit of Hacktoberfest, lots of which are either spammy or are extremely low-effort like adding and removing punctuations.
This is unfair to all of the genuine efforts that the community has been doing. Such low-effort PR's will be marked invalid to be fair with the system.

> Happy Hacking!

**Comment by mayurmadnani** [comment]
Some ideas if you want to pick:
* [Feature] Dark mode toggle with CSS
* [Feature] Go to top button on Global and India page - Completed by @arieftb
* [Improvement] Improve UI and make it more mobile friendly - Completed by @himanshu1603
* [Improvement] Animated logo - Completed by @lokeshkumar9600
* [Issue] Fixing scrolling on India page. The map takes most of the width so instead of page scroll map gets zoomed in

**Comment by corleone77** [comment]
Hi,
I'd like to add the feature [Dark mode toggle with CSS]...
;)
Thanks

**Comment by mayurmadnani** [comment]
> Hi,
> I'd like to add the feature [Dark mode toggle with CSS]...
> ;)
> Thanks

Awesome. You got it :)

**Comment by arieftb** [comment]
Hi. If you don't mind, I want to contribute for adding the feature of back to top button.

Thanks, mate. 

 :)

**Comment by mayurmadnani** [comment]
> Hi. If you don't mind, I want to contribute for adding the feature of back to top button.
> 
> Thanks, mate.
> 
> :)

Sure thing. I'll wait for your PR ;)

**Comment by himanshu1603** [comment]
Hi, I would like to improve the UI of the home page. After changing it will look like this.
![Updated UI](https://user-images.githubusercontent.com/24963056/96297770-05a22b80-100f-11eb-9d37-d55a554807c5.png)

Can I start working on this issue?

**Comment by mayurmadnani** [comment]
> Hi, I would like to improve the UI of the home page. After changing it will look like this.
> ![Updated UI](https://user-images.githubusercontent.com/24963056/96297770-05a22b80-100f-11eb-9d37-d55a554807c5.png)
> 
> Can I start working on this issue?

Looks great. You can work on it @himanshu1603

**Comment by mayurmadnani** [comment]
Thank you everyone for your submissions
#2 @CostGranda
#3 @vale-c
#4 @fazreil
#5 @arieftb 
#6 @himanshu1603
#8 #10 @lokeshkumar9600
#11 @thethiago27
